[package]
name = "zkraken-lib"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Huskehhh/zkraken-lib"
description = "A cross-platform driver library for the Kraken Z series AIO coolers written in Rust. "
license = "MIT"

[dependencies]
hidapi = "1.3.4"
color-eyre = "0.6"
